version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cognitopracticev1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-135e17ugch1hy"
s3_prefix = "cognitopracticev1"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
