AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cognito_practice_v1



Globals:
  Function:
    Timeout: 5
    Environment:
      Variables:
        COGNITO_USER_CLIENT_ID: 6cdmt1sd2hcebk640d2kvrgd13
        AWS_REGION_NAME: ap-south-1
        USER_POOL_ID: ap-south-1_Ngvo4ddCc
        APP_CLIENT_ID: 6cdmt1sd2hcebk640d2kvrgd13



Resources:
  RegisterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: my_app/
      Handler: register.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        APIForFunction1:
          Type: Api
          Properties:
            Path: /register
            Method: POST

  AccountVerificationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: my_app/
      Handler: account_verify.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        APIForFunction2:
          Type: Api
          Properties:
            Path: /verify
            Method: POST

  LoginFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: my_app/
      Handler: login.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        APIForFunction3:
          Type: Api
          Properties:
            Path: /login
            Method: POST

  VerifyTokenFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: my_app/
      Handler: verify_token.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64

  PaymentMethodFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: my_app/
      Handler: payment_method.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        APIForPaymentMethod:
          Type: Api
          Properties:
            Path: /payment_method
            Method: POST
